### ISSUE TITLE
Unclear usage permissions may conflict with the license. 

### ISSUE THREAD

**Issue by lbeltrame** [JD2112/methylr#12]
I was just browsing this repository when looking for good way to plot methylation data, and I read this sentence:

> For non-commercial Academic and Research purpose only! 

This is **not** compatible with the GPLv3 license used by the project. GPL and in general Free Software licenses (MIT, BSD, and others) do not impose restriction on usage (including for-profit, commercial usage).  However, it might have been just an oversight. 

I would suggest to the authors:

- If they don't want to allow commercial usage, to change the license accordingly;
- If instead this was just an oversight, remove the offending line from README.md
- If instead that line refers to something else, clarify the text.

**Comment by JD2112** [comment]
Hi 
Thanks for your comment. We'll remove that sentence. methylR will only has GPLv3 license.
