### ISSUE TITLE
Unable to start methylr using apptainer

### ISSUE THREAD

**Issue by WillieYu** [JD2112/methylr#3]
**Describe the bug**
Unable to start container using apptainer. 
Starting container using Docker working as expected and can access via Firefox

**To Reproduce**
#my username on my server is gmsywss
#I ran the following command as instructed
`apptainer run docker://jd21/methylr:latest`
#Below is the output
Getting image source signatures
Copying blob 675920708c8b done  
Copying blob 4a0b0c48a245 done  
Copying blob 4d225a645112 done  
Copying blob edb25e8773a2 done  
Copying blob 0859082e6bfe done  
Copying blob 2c7717ed42b5 done  
Copying blob f98488f0b7eb done  
Copying blob 68d9ec9958f4 done  
Copying blob 0907d76d45d7 done  
Copying blob 91c20754dfa7 done  
Copying blob 1cb6359be342 done  
Copying blob 039933c89bc6 done  
Copying blob a998a725ad2a done  
Copying blob eec5691985f6 done  
Copying blob c185ae260562 done  
Copying blob fb811cb38974 done  
Copying blob f7fbaa592b80 done  
Copying blob 1956e0ee4e98 done  
Copying blob 735bdb524661 done  
Copying blob 3773fe0dc9e0 done  
Copying config 530d3cb5ff done  
Writing manifest to image destination
Storing signatures
2023/07/27 12:59:18  info unpack layer: sha256:675920708c8bf10fbd02693dc8f43ee7dbe0a99cdfd55e06e6f1a8b43fd08e3f
2023/07/27 12:59:19  info unpack layer: sha256:edb25e8773a2cab31c156c1016c187b890fd7de13bb2459f52cbf0c0c4f5de79
2023/07/27 12:59:19  info unpack layer: sha256:4d225a645112c4132d5d731c26c93bc9ae072fb3021f87ae49d442af848a5c98
2023/07/27 12:59:25  info unpack layer: sha256:0859082e6bfee5b698c51c11833d63d99dee124a44288a0725fccb44f2c1487d
2023/07/27 12:59:25  info unpack layer: sha256:2c7717ed42b5b33850dc0257c03c6f35377571da4466743aa7187c8a939dfd8b
2023/07/27 12:59:26  info unpack layer: sha256:4a0b0c48a24567f3905d1c17f94e066a9437af2de554fcf2da1a43cf1200c39b
2023/07/27 12:59:30  info unpack layer: sha256:f98488f0b7ebc01b6f977a3520e6374645efd3dcb1572b6e64b51ed0c72b0a96
2023/07/27 12:59:37  info unpack layer: sha256:68d9ec9958f429496854b79a7423010ea58c683e56301db37cce4e928ba7d9b9
2023/07/27 12:59:38  info unpack layer: sha256:0907d76d45d75146c54e19628ae98241edebc344bc3ded4d18d005e0308ea28b
2023/07/27 12:59:38  info unpack layer: sha256:91c20754dfa7044fbd71855b31d811c4c8eac28943e1fb8c7b748cf90e49df97
2023/07/27 12:59:38  info unpack layer: sha256:1cb6359be342a58ff0cd8bfc996360ba99cf327e92da8b20ac1d7ea07e6201fd
2023/07/27 12:59:38  info unpack layer: sha256:039933c89bc61afe0dbf548830cffc8ec977c5575a844224c5eb65cd9d028a54
2023/07/27 12:59:55  warn rootless{usr/local/lib/R/site-library/Rhtslib/usrlib/libhts.so.2} ignoring (usually) harmless EPERM on setxattr "user.rootlesscontainers"
2023/07/27 13:00:16  info unpack layer: sha256:a998a725ad2ad2f049dd90ba75e4f0946565c315bfa58cab599ca609c84aeba1
2023/07/27 13:00:17  info unpack layer: sha256:eec5691985f610ea0f3784244e6e1348824bc84b2b77faa28770bdc6beab241c
2023/07/27 13:00:17  info unpack layer: sha256:c185ae260562a69c06c7975879b2cbc473c9d16a71ae95abd50ddbb245da6a3e
2023/07/27 13:00:18  info unpack layer: sha256:fb811cb389747dcb003f0eaadbacfab24befd161547b6be418bdf6fbf189f94c
2023/07/27 13:00:18  info unpack layer: sha256:f7fbaa592b80566757b72038746cd6dc901724af0246452d5356784a741d3feb
2023/07/27 13:00:20  info unpack layer: sha256:1956e0ee4e98aa08e0540cbabb02dd380bcc48a080bef1e1c801aabf3355b1f1
2023/07/27 13:00:20  info unpack layer: sha256:735bdb52466195ebf4ed80fb8f307649bc06a82512e1409b5bd66e799097d2c0
2023/07/27 13:00:23  info unpack layer: sha256:3773fe0dc9e08face6fcaddf24f871b39fac681ba30024f1fc85b74829e7d58d
INFO:    Creating SIF file...
[2023-07-27T05:00:38.312] [INFO] shiny-server - Shiny Server v1.5.18.979 (Node.js v12.22.6)
[2023-07-27T05:00:38.317] [INFO] shiny-server - Using config file "/etc/shiny-server/shiny-server.conf"
**[2023-07-27T05:00:38.350] [ERROR] shiny-server - Error loading config: The user 'gmsywss' does not have permissions to run applications as one of the users in 'shiny'. Please restart shiny-server as one of the users in  'shiny'. (/etc/shiny-server/shiny-server.conf:5:1)**
[2023-07-27T05:00:38.351] [INFO] shiny-server - Shutting down worker processes

**Expected behavior**
Container should be downloaded, converted to sif format then start shiny server 

**Desktop (please complete the following information):**
 - OS: CentOS8 Stream 4.18.0-500, CentOS7 (Core) 3.10.0-1160.92.1, debian11 (bullseye) 5.10.0-23
 - Browser Firefox
 - Version 115.0.2

**Comment by JD2112** [comment]
@WillieYu hej Willle, thank you very much for using methylR and reporting the bug with Singularity/Apptainer. Now we have added a script before run the Singularity container and details in README 'how to run' the Singularity container. Please let us know if this fixes your issue.

**Comment by WillieYu** [comment]
Yes, that fixes the startup issue. FYI, the prepare_template.sh script randomizes the /tmp folder and port so the actual singularity/apptainer run cmd you have in the readme is off by a little but not really an issue for me.
