### ISSUE TITLE
ChAMP analysis results in server disconnect for apptainer/singularity

### ISSUE THREAD

**Issue by WillieYu** [JD2112/methylr#4]
**Describe the bug**
I used apptainer to start the container started up. I used ChAMP pipeline on default parameters to analyze the recommended test data  set. The pipeline successfully decompressed the zip file. About 40sec into running the ChAMP pipeline, the webpage greys out and I get the "Disconnected from the server." message and asking me to reload. 
Reloading will wipe everything and bring me back to the front page. Re-running the ChAMP pipelin will result in the same server disconnect.
Nothing in the /tmp/shiny-server.xxxx/logs folder so no more information I can provide on exactly where the error is occurring.

I used docker to boot the container on my remote server and I have no issues with running the ChAMP analysis pipeline.

**To Reproduce**
This is tested to reproduce on fedora37 running apptainer 1.1.7 and CentOS8 stream running apptainer 1.1.9.
Assuming you have the testData.zip file
1) Boot up the container as per instructions for apptainer/singularity and load up methylR webpage
2) click on ChAMP analysis tab
3) click "Browse" button and upload the "testData.zip" file
4) Unzipping the file will be successful
5) At ~40 sec into the ChAMP analysis, the webpage will grey out and the "Disconnected from the server" message will show. The time to fail is very consistent across two different OS with very different hardware. 

**Expected behavior**
The analysis should complete and The "Methylation Analysis Result - ChAMP pipeline" section should be populated with graphs and tables for "QC result", "Normalized data table" and "DMC table" sub-tabs.

**Desktop (please complete the following information):**
 - OS: fedora37 6.4.6-100, CentOS8 stream 4.18.0-500
 - Container app: apptainer 1.1.7-1 .fc37, apptainer 1.1.9-1.el8, Docker 24.0.5 build ced0996
 - Browser  Firefox
 - Version 115.0.2

**Comment by JD2112** [comment]
@WillieYu Hi Willie, thanks again for reporting this issue. I checked it and it looks like some 'write permission issue' with the Singularity/Apptainer container. We will try to fix this on next update.
